### ISSUE TITLE
about the unit test

### ISSUE THREAD

**Issue by 2857** [Wiredcraft/test-frontend#6]
Hi, 
Here is the preview of my working , yet it still got some problems ,and i am fixing it . [the repo](https://github.com/aliencyl7/test-frontend) and i will finished in one day.
![work](https://cloud.githubusercontent.com/assets/5900221/16180575/8f501c2a-36bb-11e6-9b13-67e4370ac8cf.gif)

And my question is about the unit test , i am not sure about what kind of test it should be, can you explain in more detail ? thx~

**Comment by wwayne** [comment]
@aliencyl7 Since you are using Redux, I think the unit test here is, for example, testing the functions of actions and reducers, and the react components.

For function testing you can test if it returns the expected result by giving specific params.
For react component testing, you can test if it renders correctly, I usually like using Mocha + Enzyme + Sinon  + Chai, just for reference...you can use any frameworks or tools you like : )

**Comment by makara** [comment]
Hey you could send us the PR now and finish it later, so we can start the review now.

**Comment by EcutDavid** [comment]
Maybe another thing you should noticed is, this is the real mockup.
![image](https://cloud.githubusercontent.com/assets/10692276/16182420/9e207ec6-36d8-11e6-8b96-74d1d456c458.png)

For the test, It's better to implement the pixel-perfect based both on your material-ui and more importantly, designer's mockup.

**Comment by 2857** [comment]
Okay~i will send the pr right now,  and add mocha unit test and check ui responsive later

**Comment by makara** [comment]
Thanks guys. Closing.
